app:
  id: kkcloud-trainee-system
apollo:
  meta: http://172.31.24.32:48080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application
configService:
  config:
    configServiceUrlOverride: http://172.31.24.32:48080
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true