spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trainee_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  security:
    ignored: /**
  profiles:
    active: default
mybatis:
  mapperLocations: /mapper/*Mapper.xml
management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
app:
  id: kkcloud-trainee-system

#apollo:
#  autoUpdateInjectedSpringProperties: true
#  bootstrap:
#    enabled: true
#    eagerLoad:
#      enabled: true
#    namespaces: application

#spring:
#  security:
#    ignored: /**
#  profiles:
#    active: dev
#mybatis:
#  mapperLocations: /mapper/*Mapper.xml
#management:
#  endpoint:
#    health:
#      show-details: always
#  info:
#    env:
#      enabled: true
#app:
#  id: kkcloud-trainee-system
#
#apollo:
#  autoUpdateInjectedSpringProperties: true
#  bootstrap:
#    enabled: true
#    eagerLoad:
#      enabled: true
#    namespaces: application